name: Release

on:
   - push

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          cargo build --release
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: target/release/fubu*